# docker-compose.override.yml
services:
  db:
    ports:
      - "5432:5432"

  backend:
    environment:
      NODE_ENV: development
    command: npx nodemon -L serveur.js
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "5252:5252"
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Désactive le mode interne du réseau 'back' uniquement pour le dev
networks:
  back:
    internal: false